### PR TITLE
stop autoloader when matching class is found

### PR DESCRIPTION
**Pull request by cabloo**
Otherwise, tests directory is also searched.

### CODE REVIEW

**Comment by cabloo** [comment]
I signed it!

**Comment by rowan-m** [comment]
Thank you for this! I've update the Travis config separately to cover a few other issues.

**Comment by cabloo** [comment]
@rowan-m I don't think my changes got merged in with your latest merges, this change only affects `autoload.php`

**Comment by rowan-m** [comment]
@cabloo  Apologies, was trying to clean up a number of PRs and replied to the wrong one! Please feel free to resubmit and I will review.

**Comment by cabloo** [comment]
Thought that might be the case, I understand :)

Done: https://github.com/google/recaptcha/pull/146

**Pull request closed without merging**
