### PR TITLE
Add composer.json

### PR DESCRIPTION
**Pull request by barryvdh**
So people can require this library with Composer.

See https://getcomposer.org/ for more information.
After merge, this needs to be registered at https://packagist.org/

### CODE REVIEW

**Comment by franz-josef-kaiser** [comment]
+1

**Comment by BobertForever** [comment]
+1

**Comment by franz-josef-kaiser** [comment]
@BobertForever @slaughter550 @Kanti @CyberLine [There's an error-free (and maintained) composer-ready for available](https://github.com/wecodemore/ReCAPTCHA) where PRs get accepted.

**Comment by rowan-m** [comment]
Hi all, there's a new v1.1 now up that incorporates Composer support and I've pushed the package up to packagist as well. We also have a contribution process now and I'll be watching for new pull requests coming in.

**Pull request closed without merging**
