### PR TITLE
Saving some memory for echo.

### PR DESCRIPTION
**Pull request by dseguy**

### CODE REVIEW

**Comment by rowan-m** [comment]
Thanks!

**Comment by rowan-m** [comment]
@dseguy hey there, sorry I had to revert this because I missed that you hadn't actually signed the CLA. If you want to resubmit this and sign the CLA, then I'm more than happy to merge.

**Comment by dseguy** [comment]
rowan-m : I got the mail and signed the CLA. I don't know how to check it now though...

**Comment by rowan-m** [comment]
@dseguy apologies for the back and forth here. If you want to submit a new PR, then the CL bot will check it, then reply here on the thread with "I've signed it", and then the bot will go check again. A lot of bureaucracy for a small change but unfortunately necessary :(

**Comment by Rikk** [comment]
#ashamedbybureaucracy

**Comment by serbanghita** [comment]
@rowan-m according to Nick, this is not an optimization when using PHP 5.5 https://github.com/serbanghita/Mobile-Detect/pull/403#issuecomment-103515535

**Comment by nicktacular** [comment]
I wasn't aware there was a global initiative by @dseguy to replace concatenations with commas. Yes, as @serbanghita says, a quick test shows this to not be the case in current PHP.

**Comment by dseguy** [comment]
@serbanghita I also agree with you : removing the concatenation is not a speed optimization.

This is a memory usage reduction : the concatenation doubles the memory usage, right before pushing it to the browser.

**Pull request merged**
