### PR TITLE
fix PHP E_NOTICE errors

### PR DESCRIPTION
**Pull request by trinet-at**
fix PHP E_NOTICE errors, change constructor to PHP5 style, format code to adhere to PSR

### CODE REVIEW

**Comment by franz-josef-kaiser** [comment]
https://github.com/google/ReCAPTCHA/pull/11 https://github.com/google/ReCAPTCHA/pull/13 https://github.com/google/ReCAPTCHA/pull/16

**Comment by svivian** [comment]
@yingliu-google @google can someone *please* merge this PR? There are at least 10 other PRs that are duplicates of this one...

**Comment by tvb** [comment]
This is getting ridiculous :disappointed:

**Comment by franz-josef-kaiser** [comment]
If @google-admin would just transfer this repo to me...

**Comment by arthurvr** [comment]
Friendly ping for somebody to merge this :)

**Comment by franz-josef-kaiser** [comment]
As this got too annoying, we now offer [**a maintained fork**](https://github.com/wecodemore/ReCAPTCHA) where we accept pull requests (even for Ruby like in #4 and #6 ), offer better docs, Composer support (like requested in #2 ) and tagged releases with meaningful commit messages.

Currently the fork fixes all the errors in #2 #3 #5 #9 #10 #11 #13 #14 #15 #16 #20 #21 #22 #23 

The general goal will be to provide a PSR-4 compatible rewrite with version 1.0 (including the suggestions from #7 #17 #18 ).

**Comment by rowan-m** [comment]
Hi all, thank you for all the feedback here! I know it's been a while, but there is now a new v1.1 published which hopefully resolves a lot of these issues for you. Also, and perhaps more interesting for a bunch of you on this thread, there is a proper contribution process in  place now and I'll keep an eye on new pull requests.

**Pull request closed without merging**
