### PR TITLE
Add E_TIMEOUT_OR_DUPLICATE

### PR DESCRIPTION
**Pull request by ciamarro**

### CODE REVIEW

**Comment by ciamarro** [comment]
I signed it!

**Comment by rowan-m** [comment]
@ciamarro this adds a new error constant but doesn't make use of it anywhere. What's your use case / requirement here? Thanks!

**Comment by ciamarro** [comment]
Hi @rowan-m,

I was using this library for a Laravel validation rule.
It was actually one of the errors returned in $resp->getErrorCodes();
I guess my token timed out.

```
use ReCaptcha\ReCaptcha as GoogleRecaptcha;  
//...  
protected $errors;

if ($resp->isSuccess()) {
	//...
} else {
	$this->errors = $resp->getErrorCodes();
}
```
I was planning on writing the errors that weren't threshold related to an error Log and I noticed the only error that I couldn't catch was the "duplicate-or-timeout".  So basically it would be something like this:


    $log = [];  
      
    if (in_array(GoogleRecaptcha::E_INVALID_JSON, $this->errors)) {  
      $log[] = "invalid JSON";  
    }  
      
      
    if (in_array(GoogleRecaptcha::E_CONNECTION_FAILED, $this->errors)) {  
      $log[] = "connection failed";  
    }  
      
      
    if (in_array(GoogleRecaptcha::E_BAD_RESPONSE, $this->errors)) {  
      $log[] = 'bad-response';  
    }  
      
      
    if (in_array(GoogleRecaptcha::E_UNKNOWN_ERROR, $this->errors)) {  
      $log[] = 'unknown-error';  
    }  
      
      
    if (in_array(GoogleRecaptcha::E_MISSING_INPUT_RESPONSE, $this->errors)) {  
      $log[] = 'missing-input-response';  
    }  
      
      
    if (in_array(GoogleRecaptcha::E_HOSTNAME_MISMATCH, $this->errors)) {  
      $log[] = 'hostname-mismatch';  
    }  
      
      
    if (in_array(GoogleRecaptcha::E_APK_PACKAGE_NAME_MISMATCH, $this->errors)) {  
      $log[] = 'apk_package_name-mismatch';  
    }  
      
      
    if (in_array(GoogleRecaptcha::E_ACTION_MISMATCH, $this->errors)) {  
      $log[] = 'action-mismatch';  
    }  
      
      
    if (in_array(GoogleRecaptcha::E_SCORE_THRESHOLD_NOT_MET, $this->errors)) {  
      $log[] = 'score-threshold-not-met';  
    }  
      
      
    if (in_array(GoogleRecaptcha::E_CHALLENGE_TIMEOUT, $this->errors)) {  
      $log[] = 'challenge-timeout';  
    }  
      
    if (in_array(GoogleRecaptcha::E_TIMEOUT_OR_DUPLICATE, $this->errors)) {  
      $log[] = 'timeout-or-duplicate';  
    }

    $this->writeToSomeLog($log);


Thanks for your time!

**Comment by piotr-cz** [comment]
@ciamarro Why closing this PR?
I find this helpful, at least to document error code.

**Pull request closed without merging**
