### PR TITLE
Missig quotes

### PR DESCRIPTION
**Pull request by tas2580**

### CODE REVIEW

**Comment by multiwebinc** [comment]
Actually, to make things worse, `$answers['error-codes']` is not even always set, so you need to check it like this:

    if (isset($answers['error-codes'])) {
        $recaptchaResponse->errorCodes = $answers ['error-codes'];
    }

This is probably an error server-side with Google, so whoever controls this on Google's end, make sure to always set `error-codes`. In the meantime, we'll need to check it.

**Comment by tgeorge** [comment]
Thanks multiwebinc.  
I was hoping Google would of fixed this by now..but this will do for now.

**Comment by svivian** [comment]
Duplicate of #1 (and many other PRs), can you close this PR please?

**Comment by rowan-m** [comment]
Fixed in v1.1

**Pull request closed without merging**
