### PR TITLE
Fix php 8.2 creation of dynamic property is deprecated

### PR DESCRIPTION
**Pull request by 8ctopus**
Add all missing class properties to fix php 8.2 depreciations.

### CODE REVIEW

**Comment by 8ctopus** [comment]
For those looking for a solution that can be used today, I've created a fork with a branch that implements all changes needed for php 8.0, 8.1 and 8.2 compatibility here: https://github.com/8ctopus/recaptcha/commits/php8.2

To use it, you will need to update `composer.json` as follows:

```json
{
    "require": {
        "google/recaptcha": "dev-php8.2"
    },
    "repositories": [{
        "type": "git",
        "url": "https://github.com/8ctopus/recaptcha.git"
    }]
}
```

**Comment by pthreat** [comment]
Please merge this and tag to 1.2.5

**Comment by pthreat** [comment]
@8ctopus I wouldn't mind if you'd fork this entirely into a new package, package maintainer looks to be abscent overall.

**Comment by VincentLanglet** [comment]
Hi @rowan-m, I also encountered the deprecation. Do you have time to take a look to this PR ?

Thanks

**Comment by VincentLanglet** [comment]
Hi @bramp @jfschmakeit, i saw you worked on some other PHP-repository of google organization.
Maybe you
- are able to reach @rowan-m
- have rights on this one to review/merge/release this
- know who's maintaining this repository currently
?

Thanks

**Comment by rowan-m** [comment]
Key blocker here was properly updating the deps and fixing the unit tests. I've done that now, so I can merge these and then tag a new release.

**Comment by VincentLanglet** [comment]
Thanks a lot @rowan-m !

**Pull request merged**
