### PR TITLE
Bugfix in $answers array

### PR DESCRIPTION
**Pull request by stevenwoodson**
Received the error "Use of undefined constant error - assumed 'error'", adding quotes to the array key fixed the issue

### CODE REVIEW

**Comment by franz-josef-kaiser** [comment]
https://github.com/google/ReCAPTCHA/pull/11 https://github.com/google/ReCAPTCHA/pull/13

**Comment by septyaman** [comment]
good

**Comment by Lechus** [comment]
Is is just me or ['error-codes'] is not always in response?

var_dump raw response:
````
string(22) "{ "success": false }" 
````

        if (trim($answers['success']) == true) {
            $recaptchaResponse->success = true;
        } else {
            $recaptchaResponse->success = false;
            $recaptchaResponse->errorCodes = isset($answers['error-codes']) ? $answers['error-codes'] : "";
        }

**Comment by franz-josef-kaiser** [comment]
@Lechus That's [fixed in the fork](https://github.com/wecodemore/ReCAPTCHA/blob/master/php/recaptchalib.php#L131-L139)

**Comment by Lechus** [comment]
@franz-josef-kaiser : No? I am talking about cases where there is no $answers['error-codes'] in response.

**Comment by Erutan409** [comment]
Should it just default to an empty variable/array if 'error-codes' wasn't sent back in the response?

**Comment by franz-josef-kaiser** [comment]
@Lechus @Erutan409 Currently it doesn't. Google seems to ignore this repository since month. Hence the link to my reworked fork where I accept pull requests and work on issues with you.

**Comment by rowan-m** [comment]
Fixed in v1.1

**Pull request closed without merging**
